version: 2
jobs:
  build:
    docker:
      - image: img/IMG_4862.JPG
      steps:
      - run:
          name: build site and push to github-pages
          command: sh publish.sh
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
    branches:
      only:
        - master